/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Deshini
 */
public class LoginPageView extends javax.swing.JFrame {

    /**
     * Creates new form LogingPageView
     */
    public LoginPageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1Label = new javax.swing.JLabel();
        header2Label = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        exitLoging = new javax.swing.JButton();
        loging = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        header1Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1Label.setText("HOTEL MANAGEMENT SYSTEM");

        header2Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header2Label.setText("LOGING APPLICATION");

        userName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userName.setText("User Name");

        userNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Password");

        passwordText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        showPasswordCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });

        exitLoging.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLoging.setText("Exit");
        exitLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitLogingActionPerformed(evt);
            }
        });

        loging.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loging.setText("Login");
        loging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(showPasswordCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userName)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameText)
                                    .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(exitLoging)
                                .addGap(51, 51, 51)
                                .addComponent(loging)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showPasswordCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitLoging)
                    .addComponent(loging))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if (showPasswordCheckBox.isSelected()){
            passwordText.setEchoChar((char)0);
        }
        else{
            passwordText.setEchoChar('*');
        }// TODO add your handling code here:
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void exitLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitLogingActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitLogingActionPerformed

    private void logingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logingActionPerformed
        if (userNameText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your User Name.");
        }
        else if (passwordText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Password.");
        }
        else if(userNameText.getText().contains("deshini")&& passwordText.getText().contains("1234")){
            JOptionPane.showMessageDialog(null, "Login Sucessful");
            dispose();
            new MainPageView().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong User Name or Password.", "Message",JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_logingActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitLoging;
    private javax.swing.JLabel header1Label;
    private javax.swing.JLabel header2Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loging;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
